name: Dependency SUbmission

on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dotnet Info Before
        run: dotnet --info
      - name: Setup .NET Core SDK to INTENTIONALLY VULNERABLE 3.1.12 version
        uses: actions/setup-dotnet@v3.0.3
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
          dotnet-version: 3.1.12           
      - name: Dotnet Info After
        run: dotnet --info        
      - name: Build
        run: dotnet build
      - name: List Vulnerable
        run: dotnet list package --vulnerable --include-transitive
      - name: Component detection 
        uses: jhutchings1/component-detection-action@v0.0.1
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Snapshots
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          #image-ref: '.'
          github-pat: '${{ secrets.GITHUB_TOKEN }}'
