name: Dependency SUbmission

on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    strategy:
      matrix:
        runner: [ 'ubuntu-latest', 'windows-latest' ]
  
    runs-on: ${{ matrix.runner }}
    steps:      
      - name: Dotnet Info
        run: dotnet --info        
      - name: Build
        run: dotnet build
      - name: Component detection 
        ##if: runner.os != 'Windows'
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.1
        
     #- name: Run Trivy in GitHub SBOM mode and submit results to Dependency Snapshots
     #  if: runner.os != 'Windows'
     #  uses: aquasecurity/trivy-action@master
     #  with:
     #    scan-type: 'fs'
     #    format: 'github'
     #    output: 'dependency-results.sbom.json'
     #    #image-ref: '.'
     #    github-pat: '${{ secrets.GITHUB_TOKEN }}'
     
     #- uses: anchore/sbom-action@v0
     #  if: runner.os != 'Windows'
     #  with:
     #    path: .
     #    dependency-snapshot: true
